# используем язык java. Travis CI поддерживает другие языки тоже.
language: java

jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# Отправлять уведомление на почту veshousis1@gmail.com если сборка упала
notifications:
  email:
    recipients:
      -veshousis1@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
